parameters = {"Base": (None),
                "k_3_t_0.5_softmax": (3, None, 0.5, True, 'softmax'),
                "k_5_t_0.5_softmax": (5, None, 0.5, True, 'softmax'),
                "k_10_t_0.5_softmax": (10, None, 0.5, True, 'softmax'),
                "k_3_t_1.0_softmax": (3, None, 1.0, True, 'softmax'),
                "k_5_t_1.0_softmax": (5, None, 1.0, True, 'softmax'),
                "k_10_t_1.0_softmax": (10, None, 1.0, True, 'softmax'),
                "k_3_t_2.0_softmax": (3, None, 2.0, True, 'softmax'),
                "k_5_t_2.0_softmax": (5, None, 2.0, True, 'softmax'),
                "k_10_t_2.0_softmax": (10, None, 2.0, True, 'softmax'),
                "k_3_t_3.0_softmax": (3, None, 3.0, True, 'softmax'),
                "k_5_t_3.0_softmax": (5, None, 3.0, True, 'softmax'),
                "k_10_t_3.0_softmax": (10, None, 3.0, True, 'softmax'),
                "k_3_sim": (3, None, None, True, 'sim'),
                "k_4_sim": (4, None, None, True, 'sim'),
                "k_5_sim": (5, None, None, True, 'sim'),
                "k_6_sim": (6, None, None, True, 'sim'),
                "k_7_sim": (7, None, None, True, 'sim'),
                "k_8_sim": (8, None, None, True, 'sim'),
                "k_9_sim": (9, None, None, True, 'sim'),
                "k_10_sim": (10, None, None, True, 'sim'),
                "k_15_sim": (15, None, None, True, 'sim'),
                "k_10_a_09_mean": (10, 0.9, None, False, 'mean'),
                "k_10_a_08_mean": (10, 0.8, None, False, 'mean'),
                "k_10_a_07_mean": (10, 0.7, None, False, 'mean'),
                "k_10_a_06_mean": (10, 0.6, None, False, 'mean'),
                "k_10_a_05_mean": (10, 0.5, None, False, 'mean'),
                "k_10_a_04_mean": (10, 0.4, None, False, 'mean'),
                "k_10_a_03_mean": (10, 0.3, None, False, 'mean'),
                "k_10_a_02_mean": (10, 0.2, None, False, 'mean'),
                "k_10_a_01_mean": (10, 0.1, None, False, 'mean'),
                "k_7_a_09_mean": (7, 0.9, None, False, 'mean'),
                "k_7_a_08_mean": (7, 0.8, None, False, 'mean'),
                "k_7_a_07_mean": (7, 0.7, None, False, 'mean'),
                "k_7_a_06_mean": (7, 0.6, None, False, 'mean'),
                "k_7_a_05_mean": (7, 0.5, None, False, 'mean'),
                "k_7_a_04_mean": (7, 0.4, None, False, 'mean'),
                "k_7_a_03_mean": (7, 0.3, None, False, 'mean'),
                "k_7_a_02_mean": (7, 0.2, None, False, 'mean'),
                "k_7_a_01_mean": (7, 0.1, None, False, 'mean'),
                "k_5_a_09_mean": (5, 0.9, None, False, 'mean'),
                "k_5_a_08_mean": (5, 0.8, None, False, 'mean'),
                "k_5_a_07_mean": (5, 0.7, None, False, 'mean'),
                "k_5_a_06_mean": (5, 0.6, None, False, 'mean'),
                "k_5_a_05_mean": (5, 0.5, None, False, 'mean'),
                "k_5_a_04_mean": (5, 0.4, None, False, 'mean'),
                "k_5_a_03_mean": (5, 0.3, None, False, 'mean'),
                "k_5_a_02_mean": (5, 0.2, None, False, 'mean'),
                "k_5_a_01_mean": (5, 0.1, None, False, 'mean'),
                "k_3_a_09_mean": (3, 0.9, None, False, 'mean'),
                "k_3_a_08_mean": (3, 0.8, None, False, 'mean'),
                "k_3_a_07_mean": (3, 0.7, None, False, 'mean'),
                "k_3_a_06_mean": (3, 0.6, None, False, 'mean'),
                "k_3_a_05_mean": (3, 0.5, None, False, 'mean'),
                "k_3_a_04_mean": (3, 0.4, None, False, 'mean'),
                "k_3_a_03_mean": (3, 0.3, None, False, 'mean'),
                "k_3_a_02_mean": (3, 0.2, None, False, 'mean'),
                "k_3_a_01_mean": (3, 0.1, None, False, 'mean'),}


best_parameters = {"Base": (None),
                    "k_3_a_05_mean": (3, 0.5, None, False, 'mean'),
                    "k_5_a_06_mean": (5, 0.6, None, False, 'mean'),
                    "k_7_a_03_mean": (7, 0.3, None, False, 'mean'),
                    "k_5_a_02_mean": (5, 0.2, None, False, 'mean'),
                    "k_3_a_03_mean": (3, 0.3, None, False, 'mean')
                    }

test_parameters = {"k_3_a_09_mean": (3, 0.9, None, False, 'mean')}